import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LeftSideBar from './components/Sidebar'
import Navbar from './components/Navbar'
import ButtomBar from './components/Buttom'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <main className="flex flex-row">
          <LeftSideBar />
          <section className="flex min-h-screen flex-1 flex-col items-center bg-dark-1  ">
            <div className="w-full ">
              <Navbar/>
              {children}
            </div>
          </section>
          <ButtomBar/>
        </main>

      </body>
    </html>
  )
}
